export const leadsData = [
  {
    id: "lead_1",
    name: "Liam Smith",
    company: "Innovate Inc.",
    email: "liam.smith@innovateinc.com",
    source: "Website",
    score: 98,
    status: "New",
  },
  {
    id: "lead_2",
    name: "Olivia Johnson",
    company: "Data Solutions",
    email: "olivia.johnson@datasolutions.com",
    source: "Referral",
    score: 85,
    status: "Contacted",
  },
  {
    id: "lead_3",
    name: "Noah Williams",
    company: "Quantum Dynamics",
    email: "noah.williams@quantumdynamics.com",
    source: "Advertisement",
    score: 73,
    status: "Qualified",
  },
  {
    id: "lead_4",
    name: "Emma Brown",
    company: "Synergy Corp.",
    email: "emma.brown@synergycorp.com",
    source: "Cold Call",
    score: 45,
    status: "Unqualified",
  },
  {
    id: "lead_5",
    name: "Oliver Jones",
    company: "Apex Industries",
    email: "oliver.jones@apexindustries.com",
    source: "Website",
    score: 92,
    status: "New",
  },
  {
    id: "lead_6",
    name: "Ava Garcia",
    company: "Stellar Tech",
    email: "ava.garcia@stellartech.com",
    source: "Referral",
    score: 88,
    status: "Contacted",
  },
  {
    id: "lead_7",
    name: "Elijah Miller",
    company: "Horizon Enterprises",
    email: "elijah.miller@horizonenterprises.com",
    source: "Advertisement",
    score: 65,
    status: "Qualified",
  },
  {
    id: "lead_8",
    name: "Charlotte Davis",
    company: "Pinnacle Group",
    email: "charlotte.davis@pinnaclegroup.com",
    source: "Cold Call",
    score: 33,
    status: "Unqualified",
  },
  {
    id: "lead_9",
    name: "James Rodriguez",
    company: "Fusion LLC",
    email: "james.rodriguez@fusionllc.com",
    source: "Website",
    score: 95,
    status: "New",
  },
  {
    id: "lead_10",
    name: "Sophia Martinez",
    company: "Momentum Systems",
    email: "sophia.martinez@momentumsystems.com",
    source: "Referral",
    score: 79,
    status: "Contacted",
  },
  {
    id: "lead_11",
    name: "Benjamin Hernandez",
    company: "Vertex Innovations",
    email: "benjamin.hernandez@vertexinnovations.com",
    source: "Advertisement",
    score: 71,
    status: "Qualified",
  },
  {
    id: "lead_12",
    name: "Isabella Lopez",
    company: "Catalyst Co.",
    email: "isabella.lopez@catalystco.com",
    source: "Cold Call",
    score: 52,
    status: "Unqualified",
  },
  {
    id: "lead_13",
    name: "Lucas Gonzalez",
    company: "NextGen Solutions",
    email: "lucas.gonzalez@nextgensolutions.com",
    source: "Website",
    score: 99,
    status: "New",
  },
  {
    id: "lead_14",
    name: "Mia Wilson",
    company: "Evolve Technologies",
    email: "mia.wilson@evolvetechnologies.com",
    source: "Referral",
    score: 81,
    status: "Contacted",
  },
  {
    id: "lead_15",
    name: "Henry Anderson",
    company: "Ascend Dynamics",
    email: "henry.anderson@ascenddynamics.com",
    source: "Advertisement",
    score: 75,
    status: "Qualified",
  },
  {
    id: "lead_16",
    name: "Amelia Thomas",
    company: "Zenith Corp.",
    email: "amelia.thomas@zenithcorp.com",
    source: "Cold Call",
    score: 29,
    status: "Unqualified",
  },
  {
    id: "lead_17",
    name: "Alexander Taylor",
    company: "Matrix Global",
    email: "alexander.taylor@matrixglobal.com",
    source: "Website",
    score: 93,
    status: "New",
  },
  {
    id: "lead_18",
    name: "Harper Moore",
    company: "Omega Services",
    email: "harper.moore@omegaservices.com",
    source: "Referral",
    score: 84,
    status: "Contacted",
  },
  {
    id: "lead_19",
    name: "Sebastian Jackson",
    company: "Titan Industries",
    email: "sebastian.jackson@titanindustries.com",
    source: "Advertisement",
    score: 68,
    status: "Qualified",
  },
  {
    id: "lead_20",
    name: "Evelyn Martin",
    company: "Orion Partners",
    email: "evelyn.martin@orionpartners.com",
    source: "Cold Call",
    score: 41,
    status: "Unqualified",
  },
  {
    id: "lead_21",
    name: "Michael Lee",
    company: "Aperture Labs",
    email: "michael.lee@aperturelabs.com",
    source: "Website",
    score: 97,
    status: "New",
  },
  {
    id: "lead_22",
    name: "Abigail Perez",
    company: "Nova Solutions",
    email: "abigail.perez@novasolutions.com",
    source: "Referral",
    score: 89,
    status: "Contacted",
  },
  {
    id: "lead_23",
    name: "Daniel Thompson",
    company: "Silverline Inc.",
    email: "daniel.thompson@silverlineinc.com",
    source: "Advertisement",
    score: 62,
    status: "Qualified",
  },
  {
    id: "lead_24",
    name: "Emily White",
    company: "Evergreen Co.",
    email: "emily.white@evergreenco.com",
    source: "Cold Call",
    score: 38,
    status: "Unqualified",
  },
  {
    id: "lead_25",
    name: "Matthew Harris",
    company: "Summit Systems",
    email: "matthew.harris@summitsystems.com",
    source: "Website",
    score: 91,
    status: "New",
  },
  {
    id: "lead_26",
    name: "Ella Sanchez",
    company: "Blue Peak",
    email: "ella.sanchez@bluepeak.com",
    source: "Referral",
    score: 83,
    status: "Contacted",
  },
  {
    id: "lead_27",
    name: "Joseph Clark",
    company: "Redwood Corp.",
    email: "joseph.clark@redwoodcorp.com",
    source: "Advertisement",
    score: 77,
    status: "Qualified",
  },
  {
    id: "lead_28",
    name: "Avery Lewis",
    company: "Terra Firma",
    email: "avery.lewis@terrafirma.com",
    source: "Cold Call",
    score: 49,
    status: "Unqualified",
  },
  {
    id: "lead_29",
    name: "David Robinson",
    company: "Vanguard Tech",
    email: "david.robinson@vanguardtech.com",
    source: "Website",
    score: 96,
    status: "New",
  },
  {
    id: "lead_30",
    name: "Sofia Walker",
    company: "Alpha Dynamics",
    email: "sofia.walker@alphadynamics.com",
    source: "Referral",
    score: 80,
    status: "Contacted",
  },
  {
    id: "lead_31",
    name: "Jackson Young",
    company: "Bridgepoint",
    email: "jackson.young@bridgepoint.com",
    source: "Advertisement",
    score: 66,
    status: "Qualified",
  },
  {
    id: "lead_32",
    name: "Madison Allen",
    company: "Crestview",
    email: "madison.allen@crestview.com",
    source: "Cold Call",
    score: 35,
    status: "Unqualified",
  },
  {
    id: "lead_33",
    name: "Logan King",
    company: "Ironclad",
    email: "logan.king@ironclad.com",
    source: "Website",
    score: 94,
    status: "New",
  },
  {
    id: "lead_34",
    name: "Scarlett Wright",
    company: "Keystone",
    email: "scarlett.wright@keystone.com",
    source: "Referral",
    score: 86,
    status: "Contacted",
  },
  {
    id: "lead_35",
    name: "Aiden Scott",
    company: "Northstar",
    email: "aiden.scott@northstar.com",
    source: "Advertisement",
    score: 72,
    status: "Qualified",
  },
  {
    id: "lead_36",
    name: "Chloe Green",
    company: "Pathfinder",
    email: "chloe.green@pathfinder.com",
    source: "Cold Call",
    score: 43,
    status: "Unqualified",
  },
  {
    id: "lead_37",
    name: "Carter Adams",
    company: "Riverstone",
    email: "carter.adams@riverstone.com",
    source: "Website",
    score: 90,
    status: "New",
  },
  {
    id: "lead_38",
    name: "Grace Baker",
    company: "Silver Creek",
    email: "grace.baker@silvercreek.com",
    source: "Referral",
    score: 82,
    status: "Contacted",
  },
  {
    id: "lead_39",
    name: "Jayden Nelson",
    company: "Stonebridge",
    email: "jayden.nelson@stonebridge.com",
    source: "Advertisement",
    score: 69,
    status: "Qualified",
  },
  {
    id: "lead_40",
    name: "Lily Hill",
    company: "Tradewind",
    email: "lily.hill@tradewind.com",
    source: "Cold Call",
    score: 50,
    status: "Unqualified",
  },
  {
    id: "lead_41",
    name: "John Ram",
    company: "Innovate Inc.",
    email: "liam.smith@innovateinc.com",
    source: "Website",
    score: 98,
    status: "New",
  },
  {
    id: "lead_42",
    name: "Olivia Johnson",
    company: "Data Solutions",
    email: "olivia.johnson@datasolutions.com",
    source: "Referral",
    score: 85,
    status: "Contacted",
  },
  {
    id: "lead_43",
    name: "Noah Williams",
    company: "Quantum Dynamics",
    email: "noah.williams@quantumdynamics.com",
    source: "Advertisement",
    score: 73,
    status: "Qualified",
  },
  {
    id: "lead_44",
    name: "Emma Brown",
    company: "Synergy Corp.",
    email: "emma.brown@synergycorp.com",
    source: "Cold Call",
    score: 45,
    status: "Unqualified",
  },
  {
    id: "lead_45",
    name: "Oliver Jones",
    company: "Apex Industries",
    email: "oliver.jones@apexindustries.com",
    source: "Website",
    score: 92,
    status: "New",
  },
  {
    id: "lead_46",
    name: "Ava Garcia",
    company: "Stellar Tech",
    email: "ava.garcia@stellartech.com",
    source: "Referral",
    score: 88,
    status: "Contacted",
  },
  {
    id: "lead_47",
    name: "Elijah Miller",
    company: "Horizon Enterprises",
    email: "elijah.miller@horizonenterprises.com",
    source: "Advertisement",
    score: 65,
    status: "Qualified",
  },
  {
    id: "lead_48",
    name: "Charlotte Davis",
    company: "Pinnacle Group",
    email: "charlotte.davis@pinnaclegroup.com",
    source: "Cold Call",
    score: 33,
    status: "Unqualified",
  },
  {
    id: "lead_49",
    name: "James Rodriguez",
    company: "Fusion LLC",
    email: "james.rodriguez@fusionllc.com",
    source: "Website",
    score: 95,
    status: "New",
  },
  {
    id: "lead_50",
    name: "Sophia Martinez",
    company: "Momentum Systems",
    email: "sophia.martinez@momentumsystems.com",
    source: "Referral",
    score: 79,
    status: "Contacted",
  },
  {
    id: "lead_51",
    name: "Benjamin Hernandez",
    company: "Vertex Innovations",
    email: "benjamin.hernandez@vertexinnovations.com",
    source: "Advertisement",
    score: 71,
    status: "Qualified",
  },
  {
    id: "lead_52",
    name: "Isabella Lopez",
    company: "Catalyst Co.",
    email: "isabella.lopez@catalystco.com",
    source: "Cold Call",
    score: 52,
    status: "Unqualified",
  },
  {
    id: "lead_53",
    name: "Lucas Gonzalez",
    company: "NextGen Solutions",
    email: "lucas.gonzalez@nextgensolutions.com",
    source: "Website",
    score: 99,
    status: "New",
  },
  {
    id: "lead_54",
    name: "Mia Wilson",
    company: "Evolve Technologies",
    email: "mia.wilson@evolvetechnologies.com",
    source: "Referral",
    score: 81,
    status: "Contacted",
  },
  {
    id: "lead_55",
    name: "Henry Anderson",
    company: "Ascend Dynamics",
    email: "henry.anderson@ascenddynamics.com",
    source: "Advertisement",
    score: 75,
    status: "Qualified",
  },
  {
    id: "lead_56",
    name: "Amelia Thomas",
    company: "Zenith Corp.",
    email: "amelia.thomas@zenithcorp.com",
    source: "Cold Call",
    score: 29,
    status: "Unqualified",
  },
  {
    id: "lead_57",
    name: "Alexander Taylor",
    company: "Matrix Global",
    email: "alexander.taylor@matrixglobal.com",
    source: "Website",
    score: 93,
    status: "New",
  },
  {
    id: "lead_58",
    name: "Harper Moore",
    company: "Omega Services",
    email: "harper.moore@omegaservices.com",
    source: "Referral",
    score: 84,
    status: "Contacted",
  },
  {
    id: "lead_59",
    name: "Sebastian Jackson",
    company: "Titan Industries",
    email: "sebastian.jackson@titanindustries.com",
    source: "Advertisement",
    score: 68,
    status: "Qualified",
  },
  {
    id: "lead_60",
    name: "Evelyn Martin",
    company: "Orion Partners",
    email: "evelyn.martin@orionpartners.com",
    source: "Cold Call",
    score: 41,
    status: "Unqualified",
  },
  {
    id: "lead_61",
    name: "Michael Lee",
    company: "Aperture Labs",
    email: "michael.lee@aperturelabs.com",
    source: "Website",
    score: 97,
    status: "New",
  },
  {
    id: "lead_62",
    name: "Abigail Perez",
    company: "Nova Solutions",
    email: "abigail.perez@novasolutions.com",
    source: "Referral",
    score: 89,
    status: "Contacted",
  },
  {
    id: "lead_63",
    name: "Daniel Thompson",
    company: "Silverline Inc.",
    email: "daniel.thompson@silverlineinc.com",
    source: "Advertisement",
    score: 62,
    status: "Qualified",
  },
  {
    id: "lead_64",
    name: "Emily White",
    company: "Evergreen Co.",
    email: "emily.white@evergreenco.com",
    source: "Cold Call",
    score: 38,
    status: "Unqualified",
  },
  {
    id: "lead_65",
    name: "Matthew Harris",
    company: "Summit Systems",
    email: "matthew.harris@summitsystems.com",
    source: "Website",
    score: 91,
    status: "New",
  },
  {
    id: "lead_66",
    name: "Ella Sanchez",
    company: "Blue Peak",
    email: "ella.sanchez@bluepeak.com",
    source: "Referral",
    score: 83,
    status: "Contacted",
  },
  {
    id: "lead_67",
    name: "Joseph Clark",
    company: "Redwood Corp.",
    email: "joseph.clark@redwoodcorp.com",
    source: "Advertisement",
    score: 77,
    status: "Qualified",
  },
  {
    id: "lead_68",
    name: "Avery Lewis",
    company: "Terra Firma",
    email: "avery.lewis@terrafirma.com",
    source: "Cold Call",
    score: 49,
    status: "Unqualified",
  },
  {
    id: "lead_69",
    name: "David Robinson",
    company: "Vanguard Tech",
    email: "david.robinson@vanguardtech.com",
    source: "Website",
    score: 96,
    status: "New",
  },
  {
    id: "lead_70",
    name: "Sofia Walker",
    company: "Alpha Dynamics",
    email: "sofia.walker@alphadynamics.com",
    source: "Referral",
    score: 80,
    status: "Contacted",
  },
  {
    id: "lead_71",
    name: "Jackson Young",
    company: "Bridgepoint",
    email: "jackson.young@bridgepoint.com",
    source: "Advertisement",
    score: 66,
    status: "Qualified",
  },
  {
    id: "lead_72",
    name: "Madison Allen",
    company: "Crestview",
    email: "madison.allen@crestview.com",
    source: "Cold Call",
    score: 35,
    status: "Unqualified",
  },
  {
    id: "lead_73",
    name: "Logan King",
    company: "Ironclad",
    email: "logan.king@ironclad.com",
    source: "Website",
    score: 94,
    status: "New",
  },
  {
    id: "lead_74",
    name: "Scarlett Wright",
    company: "Keystone",
    email: "scarlett.wright@keystone.com",
    source: "Referral",
    score: 86,
    status: "Contacted",
  },
  {
    id: "lead_75",
    name: "Aiden Scott",
    company: "Northstar",
    email: "aiden.scott@northstar.com",
    source: "Advertisement",
    score: 72,
    status: "Qualified",
  },
  {
    id: "lead_76",
    name: "Chloe Green",
    company: "Pathfinder",
    email: "chloe.green@pathfinder.com",
    source: "Cold Call",
    score: 43,
    status: "Unqualified",
  },
  {
    id: "lead_77",
    name: "Carter Adams",
    company: "Riverstone",
    email: "carter.adams@riverstone.com",
    source: "Website",
    score: 90,
    status: "New",
  },
  {
    id: "lead_78",
    name: "Grace Baker",
    company: "Silver Creek",
    email: "grace.baker@silvercreek.com",
    source: "Referral",
    score: 82,
    status: "Contacted",
  },
  {
    id: "lead_79",
    name: "Jayden Nelson",
    company: "Stonebridge",
    email: "jayden.nelson@stonebridge.com",
    source: "Advertisement",
    score: 69,
    status: "Qualified",
  },
  {
    id: "lead_80",
    name: "Lily Hill",
    company: "Tradewind",
    email: "lily.hill@tradewind.com",
    source: "Cold Call",
    score: 50,
    status: "Unqualified",
  },
  {
    id: "lead_81",
    name: "John Ram",
    company: "Innovate Inc.",
    email: "liam.smith@innovateinc.com",
    source: "Website",
    score: 98,
    status: "New",
  },
  {
    id: "lead_82",
    name: "Olivia Johnson",
    company: "Data Solutions",
    email: "olivia.johnson@datasolutions.com",
    source: "Referral",
    score: 85,
    status: "Contacted",
  },
  {
    id: "lead_83",
    name: "Noah Williams",
    company: "Quantum Dynamics",
    email: "noah.williams@quantumdynamics.com",
    source: "Advertisement",
    score: 73,
    status: "Qualified",
  },
  {
    id: "lead_84",
    name: "Emma Brown",
    company: "Synergy Corp.",
    email: "emma.brown@synergycorp.com",
    source: "Cold Call",
    score: 45,
    status: "Unqualified",
  },
  {
    id: "lead_85",
    name: "Oliver Jones",
    company: "Apex Industries",
    email: "oliver.jones@apexindustries.com",
    source: "Website",
    score: 92,
    status: "New",
  },
  {
    id: "lead_86",
    name: "Ava Garcia",
    company: "Stellar Tech",
    email: "ava.garcia@stellartech.com",
    source: "Referral",
    score: 88,
    status: "Contacted",
  },
  {
    id: "lead_87",
    name: "Elijah Miller",
    company: "Horizon Enterprises",
    email: "elijah.miller@horizonenterprises.com",
    source: "Advertisement",
    score: 65,
    status: "Qualified",
  },
  {
    id: "lead_88",
    name: "Charlotte Davis",
    company: "Pinnacle Group",
    email: "charlotte.davis@pinnaclegroup.com",
    source: "Cold Call",
    score: 33,
    status: "Unqualified",
  },
  {
    id: "lead_89",
    name: "James Rodriguez",
    company: "Fusion LLC",
    email: "james.rodriguez@fusionllc.com",
    source: "Website",
    score: 95,
    status: "New",
  },
  {
    id: "lead_90",
    name: "Sophia Martinez",
    company: "Momentum Systems",
    email: "sophia.martinez@momentumsystems.com",
    source: "Referral",
    score: 79,
    status: "Contacted",
  },
  {
    id: "lead_91",
    name: "Benjamin Hernandez",
    company: "Vertex Innovations",
    email: "benjamin.hernandez@vertexinnovations.com",
    source: "Advertisement",
    score: 71,
    status: "Qualified",
  },
  {
    id: "lead_92",
    name: "Isabella Lopez",
    company: "Catalyst Co.",
    email: "isabella.lopez@catalystco.com",
    source: "Cold Call",
    score: 52,
    status: "Unqualified",
  },
  {
    id: "lead_93",
    name: "Lucas Gonzalez",
    company: "NextGen Solutions",
    email: "lucas.gonzalez@nextgensolutions.com",
    source: "Website",
    score: 99,
    status: "New",
  },
  {
    id: "lead_94",
    name: "Mia Wilson",
    company: "Evolve Technologies",
    email: "mia.wilson@evolvetechnologies.com",
    source: "Referral",
    score: 81,
    status: "Contacted",
  },
  {
    id: "lead_95",
    name: "Henry Anderson",
    company: "Ascend Dynamics",
    email: "henry.anderson@ascenddynamics.com",
    source: "Advertisement",
    score: 75,
    status: "Qualified",
  },
  {
    id: "lead_96",
    name: "Amelia Thomas",
    company: "Zenith Corp.",
    email: "amelia.thomas@zenithcorp.com",
    source: "Cold Call",
    score: 29,
    status: "Unqualified",
  },
  {
    id: "lead_97",
    name: "Alexander Taylor",
    company: "Matrix Global",
    email: "alexander.taylor@matrixglobal.com",
    source: "Website",
    score: 93,
    status: "New",
  },
  {
    id: "lead_98",
    name: "Harper Moore",
    company: "Omega Services",
    email: "harper.moore@omegaservices.com",
    source: "Referral",
    score: 84,
    status: "Contacted",
  },
  {
    id: "lead_99",
    name: "Sebastian Jackson",
    company: "Titan Industries",
    email: "sebastian.jackson@titanindustries.com",
    source: "Advertisement",
    score: 68,
    status: "Qualified",
  },
  {
    id: "lead_100",
    name: "Evelyn Martin",
    company: "Orion Partners",
    email: "evelyn.martin@orionpartners.com",
    source: "Cold Call",
    score: 41,
    status: "Unqualified",
  },
  {
    id: "lead_101",
    name: "Michael Lee",
    company: "Aperture Labs",
    email: "michael.lee@aperturelabs.com",
    source: "Website",
    score: 97,
    status: "New",
  },
  {
    id: "lead_102",
    name: "Abigail Perez",
    company: "Nova Solutions",
    email: "abigail.perez@novasolutions.com",
    source: "Referral",
    score: 89,
    status: "Contacted",
  },
  {
    id: "lead_103",
    name: "Daniel Thompson",
    company: "Silverline Inc.",
    email: "daniel.thompson@silverlineinc.com",
    source: "Advertisement",
    score: 62,
    status: "Qualified",
  },
  {
    id: "lead_104",
    name: "Emily White",
    company: "Evergreen Co.",
    email: "emily.white@evergreenco.com",
    source: "Cold Call",
    score: 38,
    status: "Unqualified",
  },
  {
    id: "lead_105",
    name: "Matthew Harris",
    company: "Summit Systems",
    email: "matthew.harris@summitsystems.com",
    source: "Website",
    score: 91,
    status: "New",
  },
  {
    id: "lead_106",
    name: "Ella Sanchez",
    company: "Blue Peak",
    email: "ella.sanchez@bluepeak.com",
    source: "Referral",
    score: 83,
    status: "Contacted",
  },
  {
    id: "lead_107",
    name: "Joseph Clark",
    company: "Redwood Corp.",
    email: "joseph.clark@redwoodcorp.com",
    source: "Advertisement",
    score: 77,
    status: "Qualified",
  },
  {
    id: "lead_108",
    name: "Avery Lewis",
    company: "Terra Firma",
    email: "avery.lewis@terrafirma.com",
    source: "Cold Call",
    score: 49,
    status: "Unqualified",
  },
  {
    id: "lead_109",
    name: "David Robinson",
    company: "Vanguard Tech",
    email: "david.robinson@vanguardtech.com",
    source: "Website",
    score: 96,
    status: "New",
  },
  {
    id: "lead_110",
    name: "Sofia Walker",
    company: "Alpha Dynamics",
    email: "sofia.walker@alphadynamics.com",
    source: "Referral",
    score: 80,
    status: "Contacted",
  },
  {
    id: "lead_111",
    name: "Jackson Young",
    company: "Bridgepoint",
    email: "jackson.young@bridgepoint.com",
    source: "Advertisement",
    score: 66,
    status: "Qualified",
  },
  {
    id: "lead_112",
    name: "Madison Allen",
    company: "Crestview",
    email: "madison.allen@crestview.com",
    source: "Cold Call",
    score: 35,
    status: "Unqualified",
  },
  {
    id: "lead_113",
    name: "Logan King",
    company: "Ironclad",
    email: "logan.king@ironclad.com",
    source: "Website",
    score: 94,
    status: "New",
  },
  {
    id: "lead_114",
    name: "Scarlett Wright",
    company: "Keystone",
    email: "scarlett.wright@keystone.com",
    source: "Referral",
    score: 86,
    status: "Contacted",
  },
  {
    id: "lead_115",
    name: "Aiden Scott",
    company: "Northstar",
    email: "aiden.scott@northstar.com",
    source: "Advertisement",
    score: 72,
    status: "Qualified",
  },
  {
    id: "lead_116",
    name: "Chloe Green",
    company: "Pathfinder",
    email: "chloe.green@pathfinder.com",
    source: "Cold Call",
    score: 43,
    status: "Unqualified",
  },
  {
    id: "lead_117",
    name: "Carter Adams",
    company: "Riverstone",
    email: "carter.adams@riverstone.com",
    source: "Website",
    score: 90,
    status: "New",
  },
  {
    id: "lead_118",
    name: "Grace Baker",
    company: "Silver Creek",
    email: "grace.baker@silvercreek.com",
    source: "Referral",
    score: 82,
    status: "Contacted",
  },
  {
    id: "lead_119",
    name: "Jayden Nelson",
    company: "Stonebridge",
    email: "jayden.nelson@stonebridge.com",
    source: "Advertisement",
    score: 69,
    status: "Qualified",
  },
  {
    id: "lead_120",
    name: "Lily Hill",
    company: "Tradewind",
    email: "lily.hill@tradewind.com",
    source: "Cold Call",
    score: 50,
    status: "Unqualified",
  },
  {
    id: "lead_121",
    name: "John Ram",
    company: "Innovate Inc.",
    email: "liam.smith@innovateinc.com",
    source: "Website",
    score: 98,
    status: "New",
  },
  {
    id: "lead_122",
    name: "Olivia Johnson",
    company: "Data Solutions",
    email: "olivia.johnson@datasolutions.com",
    source: "Referral",
    score: 85,
    status: "Contacted",
  },
  {
    id: "lead_123",
    name: "Noah Williams",
    company: "Quantum Dynamics",
    email: "noah.williams@quantumdynamics.com",
    source: "Advertisement",
    score: 73,
    status: "Qualified",
  },
  {
    id: "lead_124",
    name: "Emma Brown",
    company: "Synergy Corp.",
    email: "emma.brown@synergycorp.com",
    source: "Cold Call",
    score: 45,
    status: "Unqualified",
  },
  {
    id: "lead_125",
    name: "Oliver Jones",
    company: "Apex Industries",
    email: "oliver.jones@apexindustries.com",
    source: "Website",
    score: 92,
    status: "New",
  },
  {
    id: "lead_126",
    name: "Ava Garcia",
    company: "Stellar Tech",
    email: "ava.garcia@stellartech.com",
    source: "Referral",
    score: 88,
    status: "Contacted",
  },
  {
    id: "lead_127",
    name: "Elijah Miller",
    company: "Horizon Enterprises",
    email: "elijah.miller@horizonenterprises.com",
    source: "Advertisement",
    score: 65,
    status: "Qualified",
  },
  {
    id: "lead_128",
    name: "Charlotte Davis",
    company: "Pinnacle Group",
    email: "charlotte.davis@pinnaclegroup.com",
    source: "Cold Call",
    score: 33,
    status: "Unqualified",
  },
  {
    id: "lead_129",
    name: "James Rodriguez",
    company: "Fusion LLC",
    email: "james.rodriguez@fusionllc.com",
    source: "Website",
    score: 95,
    status: "New",
  },
  {
    id: "lead_130",
    name: "Sophia Martinez",
    company: "Momentum Systems",
    email: "sophia.martinez@momentumsystems.com",
    source: "Referral",
    score: 79,
    status: "Contacted",
  },
  {
    id: "lead_131",
    name: "Benjamin Hernandez",
    company: "Vertex Innovations",
    email: "benjamin.hernandez@vertexinnovations.com",
    source: "Advertisement",
    score: 71,
    status: "Qualified",
  },
  {
    id: "lead_132",
    name: "Isabella Lopez",
    company: "Catalyst Co.",
    email: "isabella.lopez@catalystco.com",
    source: "Cold Call",
    score: 52,
    status: "Unqualified",
  },
  {
    id: "lead_133",
    name: "Lucas Gonzalez",
    company: "NextGen Solutions",
    email: "lucas.gonzalez@nextgensolutions.com",
    source: "Website",
    score: 99,
    status: "New",
  },
  {
    id: "lead_134",
    name: "Mia Wilson",
    company: "Evolve Technologies",
    email: "mia.wilson@evolvetechnologies.com",
    source: "Referral",
    score: 81,
    status: "Contacted",
  },
  {
    id: "lead_135",
    name: "Henry Anderson",
    company: "Ascend Dynamics",
    email: "henry.anderson@ascenddynamics.com",
    source: "Advertisement",
    score: 75,
    status: "Qualified",
  },
  {
    id: "lead_136",
    name: "Amelia Thomas",
    company: "Zenith Corp.",
    email: "amelia.thomas@zenithcorp.com",
    source: "Cold Call",
    score: 29,
    status: "Unqualified",
  },
  {
    id: "lead_137",
    name: "Alexander Taylor",
    company: "Matrix Global",
    email: "alexander.taylor@matrixglobal.com",
    source: "Website",
    score: 93,
    status: "New",
  },
  {
    id: "lead_138",
    name: "Harper Moore",
    company: "Omega Services",
    email: "harper.moore@omegaservices.com",
    source: "Referral",
    score: 84,
    status: "Contacted",
  },
  {
    id: "lead_139",
    name: "Sebastian Jackson",
    company: "Titan Industries",
    email: "sebastian.jackson@titanindustries.com",
    source: "Advertisement",
    score: 68,
    status: "Qualified",
  },
  {
    id: "lead_140",
    name: "Evelyn Martin",
    company: "Orion Partners",
    email: "evelyn.martin@orionpartners.com",
    source: "Cold Call",
    score: 41,
    status: "Unqualified",
  },
  {
    id: "lead_141",
    name: "Michael Lee",
    company: "Aperture Labs",
    email: "michael.lee@aperturelabs.com",
    source: "Website",
    score: 97,
    status: "New",
  },
  {
    id: "lead_142",
    name: "Abigail Perez",
    company: "Nova Solutions",
    email: "abigail.perez@novasolutions.com",
    source: "Referral",
    score: 89,
    status: "Contacted",
  },
  {
    id: "lead_143",
    name: "Daniel Thompson",
    company: "Silverline Inc.",
    email: "daniel.thompson@silverlineinc.com",
    source: "Advertisement",
    score: 62,
    status: "Qualified",
  },
  {
    id: "lead_144",
    name: "Emily White",
    company: "Evergreen Co.",
    email: "emily.white@evergreenco.com",
    source: "Cold Call",
    score: 38,
    status: "Unqualified",
  },
  {
    id: "lead_145",
    name: "Matthew Harris",
    company: "Summit Systems",
    email: "matthew.harris@summitsystems.com",
    source: "Website",
    score: 91,
    status: "New",
  },
  {
    id: "lead_146",
    name: "Ella Sanchez",
    company: "Blue Peak",
    email: "ella.sanchez@bluepeak.com",
    source: "Referral",
    score: 83,
    status: "Contacted",
  },
  {
    id: "lead_147",
    name: "Joseph Clark",
    company: "Redwood Corp.",
    email: "joseph.clark@redwoodcorp.com",
    source: "Advertisement",
    score: 77,
    status: "Qualified",
  },
  {
    id: "lead_148",
    name: "Avery Lewis",
    company: "Terra Firma",
    email: "avery.lewis@terrafirma.com",
    source: "Cold Call",
    score: 49,
    status: "Unqualified",
  },
  {
    id: "lead_149",
    name: "David Robinson",
    company: "Vanguard Tech",
    email: "david.robinson@vanguardtech.com",
    source: "Website",
    score: 96,
    status: "New",
  },
  {
    id: "lead_150",
    name: "Sofia Walker",
    company: "Alpha Dynamics",
    email: "sofia.walker@alphadynamics.com",
    source: "Referral",
    score: 80,
    status: "Contacted",
  },
  {
    id: "lead_151",
    name: "Jackson Young",
    company: "Bridgepoint",
    email: "jackson.young@bridgepoint.com",
    source: "Advertisement",
    score: 66,
    status: "Qualified",
  },
  {
    id: "lead_152",
    name: "Madison Allen",
    company: "Crestview",
    email: "madison.allen@crestview.com",
    source: "Cold Call",
    score: 35,
    status: "Unqualified",
  },
  {
    id: "lead_153",
    name: "Logan King",
    company: "Ironclad",
    email: "logan.king@ironclad.com",
    source: "Website",
    score: 94,
    status: "New",
  },
  {
    id: "lead_154",
    name: "Scarlett Wright",
    company: "Keystone",
    email: "scarlett.wright@keystone.com",
    source: "Referral",
    score: 86,
    status: "Contacted",
  },
  {
    id: "lead_155",
    name: "Aiden Scott",
    company: "Northstar",
    email: "aiden.scott@northstar.com",
    source: "Advertisement",
    score: 72,
    status: "Qualified",
  },
  {
    id: "lead_156",
    name: "Chloe Green",
    company: "Pathfinder",
    email: "chloe.green@pathfinder.com",
    source: "Cold Call",
    score: 43,
    status: "Unqualified",
  },
  {
    id: "lead_157",
    name: "Carter Adams",
    company: "Riverstone",
    email: "carter.adams@riverstone.com",
    source: "Website",
    score: 90,
    status: "New",
  },
  {
    id: "lead_158",
    name: "Grace Baker",
    company: "Silver Creek",
    email: "grace.baker@silvercreek.com",
    source: "Referral",
    score: 82,
    status: "Contacted",
  },
  {
    id: "lead_159",
    name: "Jayden Nelson",
    company: "Stonebridge",
    email: "jayden.nelson@stonebridge.com",
    source: "Advertisement",
    score: 69,
    status: "Qualified",
  },
  {
    id: "lead_160",
    name: "Lily Hill",
    company: "Tradewind",
    email: "lily.hill@tradewind.com",
    source: "Cold Call",
    score: 50,
    status: "Unqualified",
  },
  {
    id: "lead_161",
    name: "John Ram",
    company: "Innovate Inc.",
    email: "liam.smith@innovateinc.com",
    source: "Website",
    score: 98,
    status: "New",
  },
  {
    id: "lead_162",
    name: "Olivia Johnson",
    company: "Data Solutions",
    email: "olivia.johnson@datasolutions.com",
    source: "Referral",
    score: 85,
    status: "Contacted",
  },
  {
    id: "lead_163",
    name: "Noah Williams",
    company: "Quantum Dynamics",
    email: "noah.williams@quantumdynamics.com",
    source: "Advertisement",
    score: 73,
    status: "Qualified",
  },
  {
    id: "lead_164",
    name: "Emma Brown",
    company: "Synergy Corp.",
    email: "emma.brown@synergycorp.com",
    source: "Cold Call",
    score: 45,
    status: "Unqualified",
  },
  {
    id: "lead_165",
    name: "Oliver Jones",
    company: "Apex Industries",
    email: "oliver.jones@apexindustries.com",
    source: "Website",
    score: 92,
    status: "New",
  },
  {
    id: "lead_166",
    name: "Ava Garcia",
    company: "Stellar Tech",
    email: "ava.garcia@stellartech.com",
    source: "Referral",
    score: 88,
    status: "Contacted",
  },
  {
    id: "lead_167",
    name: "Elijah Miller",
    company: "Horizon Enterprises",
    email: "elijah.miller@horizonenterprises.com",
    source: "Advertisement",
    score: 65,
    status: "Qualified",
  },
  {
    id: "lead_168",
    name: "Charlotte Davis",
    company: "Pinnacle Group",
    email: "charlotte.davis@pinnaclegroup.com",
    source: "Cold Call",
    score: 33,
    status: "Unqualified",
  },
  {
    id: "lead_169",
    name: "James Rodriguez",
    company: "Fusion LLC",
    email: "james.rodriguez@fusionllc.com",
    source: "Website",
    score: 95,
    status: "New",
  },
  {
    id: "lead_170",
    name: "Sophia Martinez",
    company: "Momentum Systems",
    email: "sophia.martinez@momentumsystems.com",
    source: "Referral",
    score: 79,
    status: "Contacted",
  },
  {
    id: "lead_171",
    name: "Benjamin Hernandez",
    company: "Vertex Innovations",
    email: "benjamin.hernandez@vertexinnovations.com",
    source: "Advertisement",
    score: 71,
    status: "Qualified",
  },
  {
    id: "lead_172",
    name: "Isabella Lopez",
    company: "Catalyst Co.",
    email: "isabella.lopez@catalystco.com",
    source: "Cold Call",
    score: 52,
    status: "Unqualified",
  },
  {
    id: "lead_173",
    name: "Lucas Gonzalez",
    company: "NextGen Solutions",
    email: "lucas.gonzalez@nextgensolutions.com",
    source: "Website",
    score: 99,
    status: "New",
  },
  {
    id: "lead_174",
    name: "Mia Wilson",
    company: "Evolve Technologies",
    email: "mia.wilson@evolvetechnologies.com",
    source: "Referral",
    score: 81,
    status: "Contacted",
  },
  {
    id: "lead_175",
    name: "Henry Anderson",
    company: "Ascend Dynamics",
    email: "henry.anderson@ascenddynamics.com",
    source: "Advertisement",
    score: 75,
    status: "Qualified",
  },
  {
    id: "lead_176",
    name: "Amelia Thomas",
    company: "Zenith Corp.",
    email: "amelia.thomas@zenithcorp.com",
    source: "Cold Call",
    score: 29,
    status: "Unqualified",
  },
  {
    id: "lead_177",
    name: "Alexander Taylor",
    company: "Matrix Global",
    email: "alexander.taylor@matrixglobal.com",
    source: "Website",
    score: 93,
    status: "New",
  },
  {
    id: "lead_178",
    name: "Harper Moore",
    company: "Omega Services",
    email: "harper.moore@omegaservices.com",
    source: "Referral",
    score: 84,
    status: "Contacted",
  },
  {
    id: "lead_179",
    name: "Sebastian Jackson",
    company: "Titan Industries",
    email: "sebastian.jackson@titanindustries.com",
    source: "Advertisement",
    score: 68,
    status: "Qualified",
  },
  {
    id: "lead_180",
    name: "Evelyn Martin",
    company: "Orion Partners",
    email: "evelyn.martin@orionpartners.com",
    source: "Cold Call",
    score: 41,
    status: "Unqualified",
  },
  {
    id: "lead_181",
    name: "Michael Lee",
    company: "Aperture Labs",
    email: "michael.lee@aperturelabs.com",
    source: "Website",
    score: 97,
    status: "New",
  },
  {
    id: "lead_182",
    name: "Abigail Perez",
    company: "Nova Solutions",
    email: "abigail.perez@novasolutions.com",
    source: "Referral",
    score: 89,
    status: "Contacted",
  },
  {
    id: "lead_183",
    name: "Daniel Thompson",
    company: "Silverline Inc.",
    email: "daniel.thompson@silverlineinc.com",
    source: "Advertisement",
    score: 62,
    status: "Qualified",
  },
  {
    id: "lead_184",
    name: "Emily White",
    company: "Evergreen Co.",
    email: "emily.white@evergreenco.com",
    source: "Cold Call",
    score: 38,
    status: "Unqualified",
  },
  {
    id: "lead_185",
    name: "Matthew Harris",
    company: "Summit Systems",
    email: "matthew.harris@summitsystems.com",
    source: "Website",
    score: 91,
    status: "New",
  },
  {
    id: "lead_186",
    name: "Ella Sanchez",
    company: "Blue Peak",
    email: "ella.sanchez@bluepeak.com",
    source: "Referral",
    score: 83,
    status: "Contacted",
  },
  {
    id: "lead_187",
    name: "Joseph Clark",
    company: "Redwood Corp.",
    email: "joseph.clark@redwoodcorp.com",
    source: "Advertisement",
    score: 77,
    status: "Qualified",
  },
  {
    id: "lead_188",
    name: "Avery Lewis",
    company: "Terra Firma",
    email: "avery.lewis@terrafirma.com",
    source: "Cold Call",
    score: 49,
    status: "Unqualified",
  },
  {
    id: "lead_189",
    name: "David Robinson",
    company: "Vanguard Tech",
    email: "david.robinson@vanguardtech.com",
    source: "Website",
    score: 96,
    status: "New",
  },
  {
    id: "lead_190",
    name: "Sofia Walker",
    company: "Alpha Dynamics",
    email: "sofia.walker@alphadynamics.com",
    source: "Referral",
    score: 80,
    status: "Contacted",
  },
  {
    id: "lead_191",
    name: "Jackson Young",
    company: "Bridgepoint",
    email: "jackson.young@bridgepoint.com",
    source: "Advertisement",
    score: 66,
    status: "Qualified",
  },
  {
    id: "lead_192",
    name: "Madison Allen",
    company: "Crestview",
    email: "madison.allen@crestview.com",
    source: "Cold Call",
    score: 35,
    status: "Unqualified",
  },
  {
    id: "lead_193",
    name: "Logan King",
    company: "Ironclad",
    email: "logan.king@ironclad.com",
    source: "Website",
    score: 94,
    status: "New",
  },
  {
    id: "lead_194",
    name: "Scarlett Wright",
    company: "Keystone",
    email: "scarlett.wright@keystone.com",
    source: "Referral",
    score: 86,
    status: "Contacted",
  },
  {
    id: "lead_195",
    name: "Aiden Scott",
    company: "Northstar",
    email: "aiden.scott@northstar.com",
    source: "Advertisement",
    score: 72,
    status: "Qualified",
  },
  {
    id: "lead_196",
    name: "Chloe Green",
    company: "Pathfinder",
    email: "chloe.green@pathfinder.com",
    source: "Cold Call",
    score: 43,
    status: "Unqualified",
  },
  {
    id: "lead_197",
    name: "Carter Adams",
    company: "Riverstone",
    email: "carter.adams@riverstone.com",
    source: "Website",
    score: 90,
    status: "New",
  },
  {
    id: "lead_198",
    name: "Grace Baker",
    company: "Silver Creek",
    email: "grace.baker@silvercreek.com",
    source: "Referral",
    score: 82,
    status: "Contacted",
  },
  {
    id: "lead_199",
    name: "Jayden Nelson",
    company: "Stonebridge",
    email: "jayden.nelson@stonebridge.com",
    source: "Advertisement",
    score: 69,
    status: "Qualified",
  },
  {
    id: "lead_200",
    name: "Lily Hill",
    company: "Tradewind",
    email: "lily.hill@tradewind.com",
    source: "Cold Call",
    score: 50,
    status: "Unqualified",
  },
  {
    id: "lead_201",
    name: "William Evans",
    company: "Quantum Innovations",
    email: "william.evans@quantuminnovations.com",
    source: "Website",
    score: 97,
    status: "New",
  },
  {
    id: "lead_202",
    name: "Zoe Turner",
    company: "BrightStar Solutions",
    email: "zoe.turner@brightstarsolutions.com",
    source: "Referral",
    score: 88,
    status: "Contacted",
  },
  {
    id: "lead_203",
    name: "Owen Hall",
    company: "Apex Analytics",
    email: "owen.hall@apexanalytics.com",
    source: "Advertisement",
    score: 70,
    status: "Qualified",
  },
  {
    id: "lead_204",
    name: "Victoria Collins",
    company: "Visionary Ventures",
    email: "victoria.collins@visionaryventures.com",
    source: "Cold Call",
    score: 42,
    status: "Unqualified",
  },
  {
    id: "lead_205",
    name: "Caleb Stewart",
    company: "Frontier Dynamics",
    email: "caleb.stewart@frontierdynamics.com",
    source: "Website",
    score: 96,
    status: "New",
  },
  {
    id: "lead_206",
    name: "Riley Murphy",
    company: "Golden Gate Inc.",
    email: "riley.murphy@goldengateinc.com",
    source: "Referral",
    score: 87,
    status: "Contacted",
  },
  {
    id: "lead_207",
    name: "Ryan Parker",
    company: "Helios Systems",
    email: "ryan.parker@heliossystems.com",
    source: "Advertisement",
    score: 74,
    status: "Qualified",
  },
  {
    id: "lead_208",
    name: "Aria Cook",
    company: "Infinity Works",
    email: "aria.cook@infinityworks.com",
    source: "Cold Call",
    score: 39,
    status: "Unqualified",
  },
  {
    id: "lead_209",
    name: "Nathan Edwards",
    company: "Jade Mountain",
    email: "nathan.edwards@jademountain.com",
    source: "Website",
    score: 95,
    status: "New",
  },
  {
    id: "lead_210",
    name: "Penelope Morris",
    company: "Laguna Corp",
    email: "penelope.morris@lagunacorp.com",
    source: "Referral",
    score: 81,
    status: "Contacted",
  },
  {
    id: "lead_211",
    name: "Isaac Peterson",
    company: "Meridian Group",
    email: "isaac.peterson@meridiangroup.com",
    source: "Advertisement",
    score: 76,
    status: "Qualified",
  },
  {
    id: "lead_212",
    name: "Layla Rogers",
    company: "Nebula Inc.",
    email: "layla.rogers@nebulainc.com",
    source: "Cold Call",
    score: 48,
    status: "Unqualified",
  },
  {
    id: "lead_213",
    name: "Christopher Reed",
    company: "Odyssey Ventures",
    email: "christopher.reed@odysseyventures.com",
    source: "Website",
    score: 99,
    status: "New",
  },
  {
    id: "lead_214",
    name: "Nora Bailey",
    company: "Polaris Systems",
    email: "nora.bailey@polarissystems.com",
    source: "Referral",
    score: 83,
    status: "Contacted",
  },
  {
    id: "lead_215",
    name: "Andrew Cooper",
    company: "Quasar Tech",
    email: "andrew.cooper@quasartech.com",
    source: "Advertisement",
    score: 78,
    status: "Qualified",
  },
  {
    id: "lead_216",
    name: "Stella Richardson",
    company: "Radiant Co.",
    email: "stella.richardson@radiantco.com",
    source: "Cold Call",
    score: 40,
    status: "Unqualified",
  },
  {
    id: "lead_217",
    name: "Joshua Cox",
    company: "Solstice Corp.",
    email: "joshua.cox@solsticecorp.com",
    source: "Website",
    score: 92,
    status: "New",
  },
  {
    id: "lead_218",
    name: "Hazel Howard",
    company: "Spectrum Solutions",
    email: "hazel.howard@spectrumsolutions.com",
    source: "Referral",
    score: 85,
    status: "Contacted",
  },
  {
    id: "lead_219",
    name: "Wyatt Ward",
    company: "Trident Group",
    email: "wyatt.ward@tridentgroup.com",
    source: "Advertisement",
    score: 67,
    status: "Qualified",
  },
  {
    id: "lead_220",
    name: "Paisley Brooks",
    company: "Umbra Inc.",
    email: "paisley.brooks@umbrainc.com",
    source: "Cold Call",
    score: 36,
    status: "Unqualified",
  },
  {
    id: "lead_221",
    name: "Julian Hughes",
    company: "Velocity Dynamics",
    email: "julian.hughes@velocitydynamics.com",
    source: "Website",
    score: 98,
    status: "New",
  },
  {
    id: "lead_222",
    name: "Eleanor Simmons",
    company: "Windward Co.",
    email: "eleanor.simmons@windwardco.com",
    source: "Referral",
    score: 89,
    status: "Contacted",
  },
  {
    id: "lead_223",
    name: "Levi Patterson",
    company: "Xylo Systems",
    email: "levi.patterson@xylosystems.com",
    source: "Advertisement",
    score: 71,
    status: "Qualified",
  },
  {
    id: "lead_224",
    name: "Hannah Butler",
    company: "Yarrow Inc.",
    email: "hannah.butler@yarrowinc.com",
    source: "Cold Call",
    score: 44,
    status: "Unqualified",
  },
  {
    id: "lead_225",
    name: "Aaron Foster",
    company: "Zephyr Corp.",
    email: "aaron.foster@zephyrcorp.com",
    source: "Website",
    score: 93,
    status: "New",
  },
  {
    id: "lead_226",
    name: "Audrey Gonzales",
    company: "Aura Tech",
    email: "audrey.gonzales@auratech.com",
    source: "Referral",
    score: 82,
    status: "Contacted",
  },
  {
    id: "lead_227",
    name: "Leo Henderson",
    company: "Blaze Systems",
    email: "leo.henderson@blazesystems.com",
    source: "Advertisement",
    score: 75,
    status: "Qualified",
  },
  {
    id: "lead_228",
    name: "Skylar Jenkins",
    company: "Cascade Inc.",
    email: "skylar.jenkins@cascadeinc.com",
    source: "Cold Call",
    score: 31,
    status: "Unqualified",
  },
  {
    id: "lead_229",
    name: "Lincoln Perry",
    company: "Delta Dynamics",
    email: "lincoln.perry@deltadynamics.com",
    source: "Website",
    score: 96,
    status: "New",
  },
  {
    id: "lead_230",
    name: "Claire Powell",
    company: "Echo Solutions",
    email: "claire.powell@echosolutions.com",
    source: "Referral",
    score: 86,
    status: "Contacted",
  },
  {
    id: "lead_231",
    name: "Thomas Long",
    company: "Firefly Corp.",
    email: "thomas.long@fireflycorp.com",
    source: "Advertisement",
    score: 79,
    status: "Qualified",
  },
  {
    id: "lead_232",
    name: "Addison Russell",
    company: "Galaxy Inc.",
    email: "addison.russell@galaxyinc.com",
    source: "Cold Call",
    score: 50,
    status: "Unqualified",
  },
  {
    id: "lead_233",
    name: "Mateo Griffin",
    company: "Haven Systems",
    email: "mateo.griffin@havensystems.com",
    source: "Website",
    score: 91,
    status: "New",
  },
  {
    id: "lead_234",
    name: "Samantha Diaz",
    company: "Iceberg Inc.",
    email: "samantha.diaz@iceberginc.com",
    source: "Referral",
    score: 84,
    status: "Contacted",
  },
  {
    id: "lead_235",
    name: "Elias Hayes",
    company: "Jolt Corp.",
    email: "elias.hayes@joltcorp.com",
    source: "Advertisement",
    score: 68,
    status: "Qualified",
  },
  {
    id: "lead_236",
    name: "Naomi Myers",
    company: "Kilo Tech",
    email: "naomi.myers@kilotech.com",
    source: "Cold Call",
    score: 37,
    status: "Unqualified",
  },
  {
    id: "lead_237",
    name: "Charles Ford",
    company: "Lima Solutions",
    email: "charles.ford@limasolutions.com",
    source: "Website",
    score: 94,
    status: "New",
  },
  {
    id: "lead_238",
    name: "Ariana Hamilton",
    company: "Metro Dynamics",
    email: "ariana.hamilton@metrodynamics.com",
    source: "Referral",
    score: 80,
    status: "Contacted",
  },
  {
    id: "lead_239",
    name: "Jaxon Graham",
    company: "Nimbus Inc.",
    email: "jaxon.graham@nimbusinc.com",
    source: "Advertisement",
    score: 73,
    status: "Qualified",
  },
  {
    id: "lead_240",
    name: "Everly Wallace",
    company: "Oscar Corp.",
    email: "everly.wallace@oscarcorp.com",
    source: "Cold Call",
    score: 46,
    status: "Unqualified",
  },
  {
    id: "lead_241",
    name: "Dominic Woods",
    company: "Papa Tech",
    email: "dominic.woods@papatech.com",
    source: "Website",
    score: 99,
    status: "New",
  },
  {
    id: "lead_242",
    name: "Genesis Cole",
    company: "Quebec Systems",
    email: "genesis.cole@quebecsystems.com",
    source: "Referral",
    score: 87,
    status: "Contacted",
  },
  {
    id: "lead_243",
    name: "Ezekiel West",
    company: "Romeo Inc.",
    email: "ezekiel.west@romeoinc.com",
    source: "Advertisement",
    score: 72,
    status: "Qualified",
  },
  {
    id: "lead_244",
    name: "Willow Jordan",
    company: "Sierra Dynamics",
    email: "willow.jordan@sierradynamics.com",
    source: "Cold Call",
    score: 34,
    status: "Unqualified",
  },
  {
    id: "lead_245",
    name: "Grayson Owens",
    company: "Tango Corp.",
    email: "grayson.owens@tangocorp.com",
    source: "Website",
    score: 98,
    status: "New",
  },
  {
    id: "lead_246",
    name: "Camila Reynolds",
    company: "Uniform Solutions",
    email: "camila.reynolds@uniformsolutions.com",
    source: "Referral",
    score: 83,
    status: "Contacted",
  },
  {
    id: "lead_247",
    name: "Theodore Fisher",
    company: "Victor Tech",
    email: "theodore.fisher@victortech.com",
    source: "Advertisement",
    score: 76,
    status: "Qualified",
  },
  {
    id: "lead_248",
    name: "Eliana Ellis",
    company: "Whiskey Inc.",
    email: "eliana.ellis@whiskeyinc.com",
    source: "Cold Call",
    score: 47,
    status: "Unqualified",
  },
  {
    id: "lead_249",
    name: "Kai Harrison",
    company: "X-ray Dynamics",
    email: "kai.harrison@x-raydynamics.com",
    source: "Website",
    score: 92,
    status: "New",
  },
  {
    id: "lead_250",
    name: "Eva Gibson",
    company: "Yankee Corp.",
    email: "eva.gibson@yankeecorp.com",
    source: "Referral",
    score: 85,
    status: "Contacted",
  },
  {
    id: "lead_251",
    name: "Miles Mcdonald",
    company: "Zulu Tech",
    email: "miles.mcdonald@zulutech.com",
    source: "Advertisement",
    score: 70,
    status: "Qualified",
  },
  {
    id: "lead_252",
    name: "Elena Cruz",
    company: "Alpha Bravo",
    email: "elena.cruz@alphabravo.com",
    source: "Cold Call",
    score: 32,
    status: "Unqualified",
  },
  {
    id: "lead_253",
    name: "Josiah Marshall",
    company: "Charlie Delta",
    email: "josiah.marshall@charliedelta.com",
    source: "Website",
    score: 97,
    status: "New",
  },
  {
    id: "lead_254",
    name: "Bella Ortiz",
    company: "Echo Foxtrot",
    email: "bella.ortiz@echofoxtrot.com",
    source: "Referral",
    score: 88,
    status: "Contacted",
  },
  {
    id: "lead_255",
    name: "Xavier Gomez",
    company: "Golf Hotel",
    email: "xavier.gomez@golfhotel.com",
    source: "Advertisement",
    score: 74,
    status: "Qualified",
  },
  {
    id: "lead_256",
    name: "Maya Murray",
    company: "India Juliet",
    email: "maya.murray@indiajuliet.com",
    source: "Cold Call",
    score: 39,
    status: "Unqualified",
  },
  {
    id: "lead_257",
    name: "Adam Freeman",
    company: "Kilo Lima",
    email: "adam.freeman@kilolima.com",
    source: "Website",
    score: 93,
    status: "New",
  },
  {
    id: "lead_258",
    name: "Violet Wells",
    company: "Mike November",
    email: "violet.wells@mikenovember.com",
    source: "Referral",
    score: 81,
    status: "Contacted",
  },
  {
    id: "lead_259",
    name: "Jason Webb",
    company: "Oscar Papa",
    email: "jason.webb@oscarpapa.com",
    source: "Advertisement",
    score: 78,
    status: "Qualified",
  },
  {
    id: "lead_260",
    name: "Nova Simpson",
    company: "Quebec Romeo",
    email: "nova.simpson@quebecromeo.com",
    source: "Cold Call",
    score: 41,
    status: "Unqualified",
  },
  {
    id: "lead_261",
    name: "Robert Stevens",
    company: "Sierra Tango",
    email: "robert.stevens@sierratango.com",
    source: "Website",
    score: 96,
    status: "New",
  },
  {
    id: "lead_262",
    name: "Aurora Tucker",
    company: "Uniform Victor",
    email: "aurora.tucker@uniformvictor.com",
    source: "Referral",
    score: 84,
    status: "Contacted",
  },
  {
    id: "lead_263",
    name: "Adrian Porter",
    company: "Whiskey X-ray",
    email: "adrian.porter@whiskeyx-ray.com",
    source: "Advertisement",
    score: 77,
    status: "Qualified",
  },
  {
    id: "lead_264",
    name: "Ruby Hunter",
    company: "Yankee Zulu",
    email: "ruby.hunter@yankeezulu.com",
    source: "Cold Call",
    score: 30,
    status: "Unqualified",
  },
  {
    id: "lead_265",
    name: "Kevin Hicks",
    company: "Alpha Charlie",
    email: "kevin.hicks@alphacharlie.com",
    source: "Website",
    score: 95,
    status: "New",
  },
  {
    id: "lead_266",
    name: "Natalia Crawford",
    company: "Bravo Echo",
    email: "natalia.crawford@bravoecho.com",
    source: "Referral",
    score: 80,
    status: "Contacted",
  },
  {
    id: "lead_267",
    name: "Justin Henry",
    company: "Delta Golf",
    email: "justin.henry@deltagolf.com",
    source: "Advertisement",
    score: 72,
    status: "Qualified",
  },
  {
    id: "lead_268",
    name: "Hailey Boyd",
    company: "Foxtrot India",
    email: "hailey.boyd@foxtrotindia.com",
    source: "Cold Call",
    score: 45,
    status: "Unqualified",
  },
  {
    id: "lead_269",
    name: "Brandon Mason",
    company: "Hotel Kilo",
    email: "brandon.mason@hotelkilo.com",
    source: "Website",
    score: 91,
    status: "New",
  },
  {
    id: "lead_270",
    name: "Eva Morales",
    company: "Juliet Mike",
    email: "eva.morales@julietmike.com",
    source: "Referral",
    score: 89,
    status: "Contacted",
  },
  {
    id: "lead_271",
    name: "Austin Kennedy",
    company: "Lima November",
    email: "austin.kennedy@limanovember.com",
    source: "Advertisement",
    score: 69,
    status: "Qualified",
  },
  {
    id: "lead_272",
    name: "Taylor Warren",
    company: "Oscar Quebec",
    email: "taylor.warren@oscarquebec.com",
    source: "Cold Call",
    score: 38,
    status: "Unqualified",
  },
  {
    id: "lead_273",
    name: "Jordan Armstrong",
    company: "Papa Romeo",
    email: "jordan.armstrong@paparomeo.com",
    source: "Website",
    score: 90,
    status: "New",
  },
  {
    id: "lead_274",
    name: "Kayla Hawkins",
    company: "Sierra Uniform",
    email: "kayla.hawkins@sierrauniform.com",
    source: "Referral",
    score: 85,
    status: "Contacted",
  },
  {
    id: "lead_275",
    name: "Dylan Larson",
    company: "Tango Victor",
    email: "dylan.larson@tangovictor.com",
    source: "Advertisement",
    score: 71,
    status: "Qualified",
  },
  {
    id: "lead_276",
    name: "Angelina Vasquez",
    company: "Whiskey Yankee",
    email: "angelina.vasquez@whiskeyyankee.com",
    source: "Cold Call",
    score: 40,
    status: "Unqualified",
  },
  {
    id: "lead_277",
    name: "Tyler Gilbert",
    company: "X-ray Zulu",
    email: "tyler.gilbert@x-rayzulu.com",
    source: "Website",
    score: 94,
    status: "New",
  },
  {
    id: "lead_278",
    name: "Aaliyah Olson",
    company: "Alpha Delta",
    email: "aaliyah.olson@alphadelta.com",
    source: "Referral",
    score: 82,
    status: "Contacted",
  },
  {
    id: "lead_279",
    name: "Christian Wagner",
    company: "Bravo Foxtrot",
    email: "christian.wagner@bravefoxtrot.com",
    source: "Advertisement",
    score: 75,
    status: "Qualified",
  },
  {
    id: "lead_280",
    name: "Mackenzie Snyder",
    company: "Charlie Golf",
    email: "mackenzie.snyder@charliegolf.com",
    source: "Cold Call",
    score: 42,
    status: "Unqualified",
  },
  {
    id: "lead_281",
    name: "Jose Hart",
    company: "Delta Hotel",
    email: "jose.hart@deltahotel.com",
    source: "Website",
    score: 99,
    status: "New",
  },
  {
    id: "lead_282",
    name: "Alexa Cunningham",
    company: "Echo India",
    email: "alexa.cunningham@echoindia.com",
    source: "Referral",
    score: 87,
    status: "Contacted",
  },
  {
    id: "lead_283",
    name: "Connor Bradley",
    company: "Foxtrot Juliet",
    email: "connor.bradley@foxtrotjuliet.com",
    source: "Advertisement",
    score: 78,
    status: "Qualified",
  },
  {
    id: "lead_284",
    name: "Nevaeh Lane",
    company: "Golf Kilo",
    email: "nevaeh.lane@golfkilo.com",
    source: "Cold Call",
    score: 33,
    status: "Unqualified",
  },
  {
    id: "lead_285",
    name: "Gabriel Andrews",
    company: "Hotel Lima",
    email: "gabriel.andrews@hotellima.com",
    source: "Website",
    score: 98,
    status: "New",
  },
  {
    id: "lead_286",
    name: "Peyton Fox",
    company: "India Mike",
    email: "peyton.fox@indiamike.com",
    source: "Referral",
    score: 86,
    status: "Contacted",
  },
  {
    id: "lead_287",
    name: "Jonathan Riley",
    company: "Juliet November",
    email: "jonathan.riley@julietnovember.com",
    source: "Advertisement",
    score: 79,
    status: "Qualified",
  },
  {
    id: "lead_288",
    name: "Lillian Armstrong",
    company: "Kilo Oscar",
    email: "lillian.armstrong@kilooscar.com",
    source: "Cold Call",
    score: 35,
    status: "Unqualified",
  },
  {
    id: "lead_289",
    name: "Landon Carr",
    company: "Lima Papa",
    email: "landon.carr@limapapa.com",
    source: "Website",
    score: 92,
    status: "New",
  },
  {
    id: "lead_290",
    name: "Brooklyn Howell",
    company: "Mike Quebec",
    email: "brooklyn.howell@mikequebec.com",
    source: "Referral",
    score: 84,
    status: "Contacted",
  },
  {
    id: "lead_291",
    name: "Isaiah Alvarez",
    company: "November Romeo",
    email: "isaiah.alvarez@novemberromeo.com",
    source: "Advertisement",
    score: 76,
    status: "Qualified",
  },
  {
    id: "lead_292",
    name: "Serenity Morrison",
    company: "Oscar Sierra",
    email: "serenity.morrison@oscarsierra.com",
    source: "Cold Call",
    score: 49,
    status: "Unqualified",
  },
  {
    id: "lead_293",
    name: "Dominic Hansen",
    company: "Papa Tango",
    email: "dominic.hansen@papatango.com",
    source: "Website",
    score: 91,
    status: "New",
  },
  {
    id: "lead_294",
    name: "Caroline Fernandez",
    company: "Quebec Uniform",
    email: "caroline.fernandez@quebecuniform.com",
    source: "Referral",
    score: 83,
    status: "Contacted",
  },
  {
    id: "lead_295",
    name: "Jeremiah Garza",
    company: "Romeo Victor",
    email: "jeremiah.garza@romeovictor.com",
    source: "Advertisement",
    score: 70,
    status: "Qualified",
  },
  {
    id: "lead_296",
    name: "Madelyn Harvey",
    company: "Sierra Whiskey",
    email: "madelyn.harvey@sierrawhiskey.com",
    source: "Cold Call",
    score: 36,
    status: "Unqualified",
  },
  {
    id: "lead_297",
    name: "Elias Little",
    company: "Tango X-ray",
    email: "elias.little@tangox-ray.com",
    source: "Website",
    score: 94,
    status: "New",
  },
  {
    id: "lead_298",
    name: "Kennedy Burton",
    company: "Uniform Yankee",
    email: "kennedy.burton@uniformyankee.com",
    source: "Referral",
    score: 89,
    status: "Contacted",
  },
  {
    id: "lead_299",
    name: "Blake Banks",
    company: "Victor Zulu",
    email: "blake.banks@victorzulu.com",
    source: "Advertisement",
    score: 77,
    status: "Qualified",
  },
  {
    id: "lead_300",
    name: "Genesis Franklin",
    company: "Whiskey Alpha",
    email: "genesis.franklin@whiskeyalpha.com",
    source: "Cold Call",
    score: 37,
    status: "Unqualified",
  },
];
